export default {
    LOGOUT: 'LOGOUT',
    CLEAR_MESSAGES: 'CLEAR_MESSAGES',
    SET_SELECTED_MENU: 'SET_SELECTED_MENU',
    SET_SELECTED_ITEM: 'SET_SELECTED_ITEM',
    SET_ERROR_MSG: 'SET_ERROR_MSG',
    SET_SUCCESS_MSG: 'SET_SUCCESS_MSG',
    FETCH_USER_INFO_REQUEST: 'FETCH_USER_INFO_REQUEST',
    FETCH_USER_INFO_FAILURE: 'FETCH_USER_INFO_FAILURE',
    FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
    FETCH_LOGIN_REQUEST: 'FETCH_LOGIN_REQUEST',
    FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',
    CLEAR_FORM_VALUES: 'CLEAR_FORM_VALUES'
}